/**
 * TypeScript type definitions for the Remotion to After Effects export manifest format.
 *
 * These types describe the JSON structure generated by the ae-exporter module
 * and consumed by the After Effects ExtendScript plugin.
 */

/**
 * Root manifest object containing all export data
 */
export interface RemotionExportManifest {
  /** Manifest format version */
  version: '1.0';

  /** Composition metadata */
  metadata: ManifestMetadata;

  /** Theme configuration (optional) */
  theme: ThemeDefinition | null;

  /** Array of composition definitions (main comp + scene comps) */
  compositions: Composition[];

  /** Available easing presets for reference */
  easingPresets: Record<string, [number, number, number, number]>;
}

/**
 * Composition/video metadata
 */
export interface ManifestMetadata {
  /** Composition name */
  name: string;

  /** Width in pixels */
  width: number;

  /** Height in pixels */
  height: number;

  /** Frames per second */
  fps: number;

  /** Total duration in frames */
  durationInFrames: number;

  /** Total duration in seconds */
  durationInSeconds: number;

  /** ISO timestamp of export */
  exportedAt: string;

  /** Source application identifier */
  source: string;
}

/**
 * Theme/styling configuration
 */
export interface ThemeDefinition {
  /** Theme ID */
  id: string;

  /** Theme display name */
  name: string;

  /** Color palette */
  colors: ThemeColors;

  /** Font families */
  fonts: ThemeFonts;
}

export interface ThemeColors {
  /** Main background color (hex) */
  background: string;

  /** Optional gradient background */
  backgroundGradient?: string;

  /** Primary text color (hex) */
  textPrimary: string;

  /** Secondary/muted text color (hex) */
  textSecondary: string;

  /** Primary accent color (hex) */
  accent: string;

  /** Secondary accent color (hex) */
  accentSecondary?: string;

  /** Surface/card background color */
  surface?: string;

  /** Light surface variant */
  surfaceLight?: string;
}

export interface ThemeFonts {
  /** Heading font family */
  heading: string;

  /** Body text font family */
  body: string;
}

/**
 * Composition definition (main comp or scene precomp)
 */
export interface Composition {
  /** Unique composition ID */
  id: string;

  /** Composition display name */
  name: string;

  /** Start frame (for scene comps) */
  inPoint?: number;

  /** End frame (for scene comps) */
  outPoint?: number;

  /** Duration in frames (for scene comps) */
  durationInFrames?: number;

  /** Array of layers in this composition */
  layers: Layer[];
}

/**
 * Layer definition
 */
export interface Layer {
  /** Unique layer ID */
  id: string;

  /** Layer type */
  type: LayerType;

  /** Layer display name */
  name: string;

  /** Layer start frame */
  inPoint: number;

  /** Layer end frame */
  outPoint: number;

  /** Animated properties for this layer */
  properties: AnimatedProperty[];

  /** Type-specific content */
  content?: LayerContent;

  /** CSS blend mode */
  blendMode?: BlendMode;

  /** Effects applied to this layer */
  effects?: EffectDefinition[];

  /** Clip-path/mask definition */
  clipPath?: ClipPathDefinition;

  /** Spring animations */
  springs?: SpringDefinition[];

  /** Expression animations */
  expressions?: ExpressionDefinition[];
}

/**
 * Supported layer types
 */
export type LayerType =
  | 'solid'
  | 'text'
  | 'shape'
  | 'image'
  | 'null'
  | 'precomp';

/**
 * Union type for layer content based on layer type
 */
export type LayerContent =
  | SolidContent
  | TextContent
  | ShapeContent
  | ImageContent
  | PrecompContent;

/**
 * Solid layer content
 */
export interface SolidContent {
  /** Fill color (hex) */
  color: string;

  /** Width in pixels */
  width: number;

  /** Height in pixels */
  height: number;
}

/**
 * Text layer content
 */
export interface TextContent {
  /** Text string */
  text: string;

  /** Font size in points */
  fontSize: number;

  /** Font family name */
  fontFamily: string;

  /** Font weight (100-900) */
  fontWeight?: number;

  /** Font style (normal, italic) */
  fontStyle?: 'normal' | 'italic';

  /** Text color (hex) */
  color: string;

  /** Text alignment */
  textAlign: 'left' | 'center' | 'right';

  /** Position [x, y] */
  position: [number, number];
}

/**
 * Shape layer content
 */
export interface ShapeContent {
  /** Shape type */
  shapeType: 'rectangle' | 'rect' | 'ellipse' | 'circle';

  /** Width (for rectangles) */
  width?: number;

  /** Height (for rectangles) */
  height?: number;

  /** Radius (for circles) */
  radius?: number;

  /** Corner roundness (for rectangles) */
  roundness?: number;

  /** Fill color (hex) */
  fillColor?: string;

  /** Fill opacity (0-100) */
  fillOpacity?: number;

  /** Stroke color (hex) */
  strokeColor?: string;

  /** Stroke width */
  strokeWidth?: number;
}

/**
 * Image layer content (placeholder)
 */
export interface ImageContent {
  /** Source URL or path */
  source: string;

  /** Position [x, y] */
  position?: [number, number];

  /** Scale [x, y] as percentage */
  scale?: [number, number];
}

/**
 * Precomp layer content
 */
export interface PrecompContent {
  /** ID of the source composition */
  compositionId: string;
}

/**
 * Animated property definition
 */
export interface AnimatedProperty {
  /** Property name (position, scale, opacity, rotation) */
  name: AnimatablePropertyName;

  /** Array of keyframes */
  keyframes: Keyframe[];

  /** Optional expression for complex animations */
  expression?: string;
}

/**
 * Supported animatable property names
 */
export type AnimatablePropertyName =
  | 'position'
  | 'scale'
  | 'opacity'
  | 'rotation'
  | 'anchorPoint';

/**
 * Keyframe definition
 */
export interface Keyframe {
  /** Frame number */
  frame: number;

  /** Value at this keyframe (number for 1D, array for multi-dimensional) */
  value: number | number[];

  /** Easing to apply after this keyframe */
  easing: EasingDefinition;
}

/**
 * Easing definition
 */
export interface EasingDefinition {
  /** Easing type */
  type: EasingType;

  /** Cubic bezier control points for 'bezier' type */
  bezier?: [number, number, number, number];

  /** Preset name for 'preset' type */
  preset?: string;

  /** Expression string for 'expression' type */
  expression?: string;
}

/**
 * Supported easing types
 */
export type EasingType =
  | 'linear'
  | 'bezier'
  | 'hold'
  | 'preset'
  | 'expression';

/**
 * Standard easing preset names
 */
export type EasingPresetName =
  | 'linear'
  | 'ease'
  | 'ease-in'
  | 'ease-out'
  | 'ease-in-out'
  | 'ease-in-quad'
  | 'ease-out-quad'
  | 'ease-in-out-quad'
  | 'ease-in-cubic'
  | 'ease-out-cubic'
  | 'ease-in-out-cubic'
  | 'ease-in-quart'
  | 'ease-out-quart'
  | 'ease-in-out-quart'
  | 'ease-in-quint'
  | 'ease-out-quint'
  | 'ease-in-out-quint'
  | 'ease-in-expo'
  | 'ease-out-expo'
  | 'ease-in-out-expo'
  | 'ease-in-circ'
  | 'ease-out-circ'
  | 'ease-in-out-circ'
  | 'ease-in-back'
  | 'ease-out-back'
  | 'ease-in-out-back';

// =====================
// Enhanced Layer Features
// =====================

/**
 * CSS blend modes
 */
export type BlendMode =
  | 'normal'
  | 'multiply'
  | 'screen'
  | 'overlay'
  | 'darken'
  | 'lighten'
  | 'color-dodge'
  | 'color-burn'
  | 'hard-light'
  | 'soft-light'
  | 'difference'
  | 'exclusion'
  | 'hue'
  | 'saturation'
  | 'color'
  | 'luminosity';

/**
 * Effect definition
 */
export interface EffectDefinition {
  /** Effect type */
  type: EffectType;

  /** Effect value (for single-value effects) */
  value?: number | string;

  /** Shadow-specific properties */
  shadow?: {
    offsetX: number;
    offsetY: number;
    blurRadius: number;
    color?: [number, number, number] | string;
  };

  /** Effect-specific options */
  options?: Record<string, number | string | boolean | number[]>;

  /** Property name for keyframe animation */
  propertyName?: string;

  /** Keyframes for animated effects */
  keyframes?: EffectKeyframe[];
}

/**
 * Effect types
 */
export type EffectType =
  | 'blur'
  | 'brightness'
  | 'contrast'
  | 'saturate'
  | 'hue-rotate'
  | 'grayscale'
  | 'invert'
  | 'sepia'
  | 'drop-shadow'
  | 'glow'
  | 'turbulent-displace'
  | 'gradient-ramp'
  | 'fractal-noise';

/**
 * Effect keyframe
 */
export interface EffectKeyframe {
  /** Frame number */
  frame: number;

  /** Value at this keyframe */
  value: number | number[];
}

/**
 * Clip-path/mask definition
 */
export interface ClipPathDefinition {
  /** Clip-path type */
  type: ClipPathType;

  /** Inset values (for inset type) */
  values?: {
    top: number;
    right: number;
    bottom: number;
    left: number;
  };

  /** Whether values are percentages */
  isPercent?: boolean;

  /** Circle radius */
  radius?: number;

  /** Radius unit */
  radiusUnit?: 'px' | '%';

  /** Center X position */
  centerX?: number;

  /** Center Y position */
  centerY?: number;

  /** Center position unit */
  centerUnit?: 'px' | '%';

  /** Ellipse X radius */
  radiusX?: number;

  /** Ellipse Y radius */
  radiusY?: number;

  /** Polygon points */
  points?: ClipPathPoint[];

  /** SVG path d attribute */
  d?: string;

  /** Mask options */
  options?: MaskOptions;
}

/**
 * Clip-path types
 */
export type ClipPathType =
  | 'inset'
  | 'circle'
  | 'ellipse'
  | 'polygon'
  | 'path';

/**
 * Polygon point
 */
export interface ClipPathPoint {
  /** X coordinate */
  x: number;

  /** Y coordinate */
  y: number;

  /** X unit */
  xUnit: 'px' | '%';

  /** Y unit */
  yUnit: 'px' | '%';
}

/**
 * Mask options
 */
export interface MaskOptions {
  /** Mask mode */
  mode?: 'add' | 'subtract' | 'intersect' | 'lighten' | 'darken' | 'difference' | 'none';

  /** Mask feather */
  feather?: number;

  /** Mask opacity */
  opacity?: number;

  /** Mask expansion */
  expansion?: number;

  /** Inverted mask */
  inverted?: boolean;
}

/**
 * Spring animation definition
 */
export interface SpringDefinition {
  /** Property to animate */
  property: AnimatablePropertyName;

  /** Start value */
  startValue: number | number[];

  /** End value */
  endValue: number | number[];

  /** Start frame */
  startFrame?: number;

  /** Spring configuration */
  config?: SpringConfig;
}

/**
 * Spring physics configuration
 */
export interface SpringConfig {
  /** Damping ratio (default: 10) */
  damping?: number;

  /** Mass (default: 1) */
  mass?: number;

  /** Stiffness (default: 100) */
  stiffness?: number;

  /** Clamp overshoot (default: false) */
  overshootClamping?: boolean;
}

/**
 * Expression animation definition
 */
export interface ExpressionDefinition {
  /** Property to apply expression to */
  property: AnimatablePropertyName;

  /** The expression code */
  expression: string;

  /** Expression type hint */
  type?: ExpressionType;
}

/**
 * Expression types
 */
export type ExpressionType =
  | 'spring'
  | 'interpolate'
  | 'sine-wave'
  | 'wiggle'
  | 'loop'
  | 'circular-motion'
  | 'inertia'
  | 'typewriter'
  | 'counter'
  | 'custom';

/**
 * Gradient definition (for background layers)
 */
export interface GradientDefinition {
  /** Gradient type */
  type: 'linear' | 'radial';

  /** Color stops */
  stops: GradientStop[];

  /** Angle in degrees (for linear gradients) */
  angle?: number;

  /** Center position (for radial gradients) */
  center?: [number, number];

  /** Radius (for radial gradients) */
  radius?: number;
}

/**
 * Gradient color stop
 */
export interface GradientStop {
  /** Color (hex or RGB array) */
  color: string | [number, number, number];

  /** Position (0-100) */
  position: number;

  /** Opacity (0-100) */
  opacity?: number;
}
