/**
 * Remotion to After Effects Importer
 * Main entry point for the AE ExtendScript plugin
 *
 * This script imports Remotion composition manifests (JSON) into After Effects,
 * recreating the layer structure, animations, and timing.
 *
 * Usage:
 * 1. Export a manifest JSON from Remotion using the export API
 * 2. In After Effects: File > Scripts > Run Script File...
 * 3. Select this file and choose the manifest JSON when prompted
 *
 * Or use the self-contained script generated by the export API.
 */

// Include library files (relative paths from script location)
#include "lib/bezier-easing.jsx"
#include "lib/layer-factory.jsx"
#include "lib/keyframe-utils.jsx"
#include "lib/effects-mapping.jsx"
#include "lib/mask-utils.jsx"
#include "lib/expression-generator.jsx"

(function() {
  'use strict';

  // =====================
  // Configuration
  // =====================

  var CONFIG = {
    version: '1.0.0',
    defaultFps: 30,
    defaultWidth: 1920,
    defaultHeight: 1080,
  };

  // =====================
  // Blend Mode Mapping
  // =====================

  var BLEND_MODE_MAP = {
    'normal': BlendingMode.NORMAL,
    'multiply': BlendingMode.MULTIPLY,
    'screen': BlendingMode.SCREEN,
    'overlay': BlendingMode.OVERLAY,
    'darken': BlendingMode.DARKEN,
    'lighten': BlendingMode.LIGHTEN,
    'color-dodge': BlendingMode.COLOR_DODGE,
    'color-burn': BlendingMode.COLOR_BURN,
    'hard-light': BlendingMode.HARD_LIGHT,
    'soft-light': BlendingMode.SOFT_LIGHT,
    'difference': BlendingMode.DIFFERENCE,
    'exclusion': BlendingMode.EXCLUSION,
    'hue': BlendingMode.HUE,
    'saturation': BlendingMode.SATURATION,
    'color': BlendingMode.COLOR,
    'luminosity': BlendingMode.LUMINOSITY
  };

  // =====================
  // File I/O Utilities
  // =====================

  /**
   * Read and parse a JSON file
   * @param {File} file - The file object to read
   * @returns {Object|null} Parsed JSON or null on error
   */
  function readJsonFile(file) {
    try {
      if (!file.exists) {
        alert('File does not exist: ' + file.fsName);
        return null;
      }

      file.open('r');
      var content = file.read();
      file.close();

      // Parse JSON (ExtendScript doesn't have native JSON)
      return evalJson(content);
    } catch (e) {
      alert('Error reading file: ' + e.message);
      return null;
    }
  }

  /**
   * Parse JSON string (ExtendScript polyfill)
   * @param {string} str - JSON string
   * @returns {Object} Parsed object
   */
  function evalJson(str) {
    // Basic JSON parser for ExtendScript
    // Note: This uses eval which is not ideal but necessary for ExtendScript
    try {
      // Sanitize the string to prevent code injection
      // Only allow JSON-safe characters
      if (!/^[\],:{}\s]*$/.test(str.replace(/\\["\\\/bfnrtu]/g, '@')
          .replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g, ']')
          .replace(/(?:^|:|,)(?:\s*\[)+/g, ''))) {
        throw new Error('Invalid JSON');
      }
      return eval('(' + str + ')');
    } catch (e) {
      alert('JSON parse error: ' + e.message);
      return null;
    }
  }

  /**
   * Prompt user to select a manifest file
   * @returns {File|null} Selected file or null
   */
  function selectManifestFile() {
    var file = File.openDialog('Select Remotion Export Manifest', 'JSON Files:*.json');
    return file;
  }

  // =====================
  // Composition Creation
  // =====================

  /**
   * Create the main composition from manifest metadata
   * @param {Object} metadata - Manifest metadata
   * @returns {CompItem} Created composition
   */
  function createMainComposition(metadata) {
    var comp = app.project.items.addComp(
      metadata.name || 'Remotion Import',
      metadata.width || CONFIG.defaultWidth,
      metadata.height || CONFIG.defaultHeight,
      1, // pixel aspect ratio
      metadata.durationInSeconds || 10,
      metadata.fps || CONFIG.defaultFps
    );

    return comp;
  }

  /**
   * Create a scene composition
   * @param {Object} compData - Composition data from manifest
   * @param {Object} metadata - Global metadata
   * @returns {CompItem} Created composition
   */
  function createSceneComposition(compData, metadata) {
    var duration = (compData.durationInFrames || 90) / (metadata.fps || CONFIG.defaultFps);

    var comp = app.project.items.addComp(
      compData.name || 'Scene',
      metadata.width || CONFIG.defaultWidth,
      metadata.height || CONFIG.defaultHeight,
      1,
      duration,
      metadata.fps || CONFIG.defaultFps
    );

    return comp;
  }

  // =====================
  // Layer Enhancement Functions
  // =====================

  /**
   * Apply blend mode to a layer
   * @param {Layer} layer - The AE layer
   * @param {string} blendMode - CSS blend mode name
   */
  function applyBlendMode(layer, blendMode) {
    if (!blendMode || blendMode === 'normal') return;

    var aeMode = BLEND_MODE_MAP[blendMode];
    if (aeMode) {
      try {
        layer.blendingMode = aeMode;
      } catch (e) {
        // Blend mode not supported for this layer type
      }
    }
  }

  /**
   * Apply effects from manifest to a layer
   * @param {Layer} layer - The AE layer
   * @param {Array} effects - Array of effect definitions
   * @param {number} fps - Frames per second
   */
  function applyLayerEffects(layer, effects, fps) {
    if (!effects || effects.length === 0) return;

    for (var i = 0; i < effects.length; i++) {
      var effectDef = effects[i];
      var effect = null;

      switch (effectDef.type) {
        case 'blur':
          effect = EffectsMapping.convertBlur(effectDef.value, layer);
          break;
        case 'brightness':
          effect = EffectsMapping.convertBrightness(effectDef.value, layer);
          break;
        case 'contrast':
          effect = EffectsMapping.convertContrast(effectDef.value, layer);
          break;
        case 'saturate':
          effect = EffectsMapping.convertSaturate(effectDef.value, layer);
          break;
        case 'hue-rotate':
          effect = EffectsMapping.convertHueRotate(effectDef.value, layer);
          break;
        case 'grayscale':
          effect = EffectsMapping.convertGrayscale(effectDef.value, layer);
          break;
        case 'invert':
          effect = EffectsMapping.convertInvert(effectDef.value, layer);
          break;
        case 'sepia':
          effect = EffectsMapping.convertSepia(effectDef.value, layer);
          break;
        case 'drop-shadow':
          if (effectDef.shadow) {
            effect = EffectsMapping.convertDropShadow(
              effectDef.shadow.offsetX || 0,
              effectDef.shadow.offsetY || 0,
              effectDef.shadow.blurRadius || 0,
              effectDef.shadow.color || null,
              layer
            );
          }
          break;
        case 'glow':
          effect = EffectsMapping.applyGlow(layer, effectDef.options || {});
          break;
        case 'turbulent-displace':
          effect = EffectsMapping.applyTurbulentDisplace(layer, effectDef.options || {});
          break;
        case 'gradient-ramp':
          effect = EffectsMapping.applyGradientRamp(layer, effectDef.options || {});
          break;
        case 'fractal-noise':
          effect = EffectsMapping.applyFractalNoise(layer, effectDef.options || {});
          break;
      }

      // Apply keyframes to effect if provided
      if (effect && effectDef.keyframes) {
        applyEffectKeyframes(effect, effectDef, fps);
      }
    }
  }

  /**
   * Apply keyframes to an effect property
   * @param {Effect} effect - The AE effect
   * @param {Object} effectDef - Effect definition with keyframes
   * @param {number} fps - Frames per second
   */
  function applyEffectKeyframes(effect, effectDef, fps) {
    if (!effectDef.keyframes || !effectDef.propertyName) return;

    try {
      var prop = effect.property(effectDef.propertyName);
      if (prop && prop.canVaryOverTime) {
        for (var i = 0; i < effectDef.keyframes.length; i++) {
          var kf = effectDef.keyframes[i];
          var time = kf.frame / fps;
          prop.setValueAtTime(time, kf.value);
        }
      }
    } catch (e) {
      // Effect keyframe application failed
    }
  }

  /**
   * Apply mask/clip-path to a layer
   * @param {Layer} layer - The AE layer
   * @param {Object} clipPath - Clip-path definition
   */
  function applyLayerMask(layer, clipPath) {
    if (!clipPath) return;

    var mask = MaskUtils.createMaskFromClipPath(layer, clipPath);

    if (mask && clipPath.options) {
      MaskUtils.setMaskProperties(mask, clipPath.options);
    }
  }

  /**
   * Apply spring expression animation to a property
   * @param {Layer} layer - The AE layer
   * @param {Object} springDef - Spring animation definition
   * @param {number} fps - Frames per second
   */
  function applySpringAnimation(layer, springDef, fps) {
    if (!springDef || !springDef.property) return;

    var prop = KeyframeUtils.getLayerProperty(layer, springDef.property);
    if (!prop || !prop.canSetExpression) return;

    var expression = ExpressionGenerator.springExpression(
      springDef.config || {},
      springDef.startValue,
      springDef.endValue,
      springDef.startFrame || 0
    );

    try {
      prop.expression = expression;
    } catch (e) {
      // Expression application failed
    }
  }

  /**
   * Process all enhancements for a layer
   * @param {Layer} layer - The AE layer
   * @param {Object} layerData - Layer data from manifest
   * @param {number} fps - Frames per second
   */
  function processLayerEnhancements(layer, layerData, fps) {
    // Apply blend mode
    if (layerData.blendMode) {
      applyBlendMode(layer, layerData.blendMode);
    }

    // Apply effects
    if (layerData.effects) {
      applyLayerEffects(layer, layerData.effects, fps);
    }

    // Apply mask/clip-path
    if (layerData.clipPath) {
      applyLayerMask(layer, layerData.clipPath);
    }

    // Apply spring animations
    if (layerData.springs) {
      for (var i = 0; i < layerData.springs.length; i++) {
        applySpringAnimation(layer, layerData.springs[i], fps);
      }
    }

    // Apply other expression animations
    if (layerData.expressions) {
      for (var j = 0; j < layerData.expressions.length; j++) {
        var exprDef = layerData.expressions[j];
        var prop = KeyframeUtils.getLayerProperty(layer, exprDef.property);
        if (prop && prop.canSetExpression && exprDef.expression) {
          try {
            prop.expression = exprDef.expression;
          } catch (e) {
            // Expression failed
          }
        }
      }
    }
  }

  // =====================
  // Import Processing
  // =====================

  /**
   * Process and import a complete manifest
   * @param {Object} manifest - The parsed manifest object
   * @returns {CompItem} The main composition
   */
  function processManifest(manifest) {
    if (!manifest || !manifest.metadata) {
      alert('Invalid manifest: missing metadata');
      return null;
    }

    var meta = manifest.metadata;
    var fps = meta.fps || CONFIG.defaultFps;

    // Create progress window
    var progress = new Window('palette', 'Importing Remotion Composition');
    progress.add('statictext', undefined, 'Processing...');
    var progressBar = progress.add('progressbar', undefined, 0, 100);
    progressBar.preferredSize.width = 300;
    progress.show();

    try {
      // Step 1: Create scene compositions (all except main)
      var compMap = {};
      var sceneComps = manifest.compositions.slice(1); // Skip main comp
      var totalSteps = sceneComps.length + 1;
      var currentStep = 0;

      for (var i = 0; i < sceneComps.length; i++) {
        var sceneData = sceneComps[i];
        progress.children[0].text = 'Creating scene: ' + (sceneData.name || ('Scene ' + (i + 1)));
        progressBar.value = (currentStep / totalSteps) * 100;

        // Create scene composition
        var sceneComp = createSceneComposition(sceneData, meta);

        // Create layers in reverse order (AE stacks from bottom up)
        var layers = sceneData.layers || [];
        for (var j = layers.length - 1; j >= 0; j--) {
          var layerData = layers[j];
          var layer = LayerFactory.createLayer(sceneComp, layerData, fps);

          if (layer) {
            // Apply standard keyframe animations
            if (layerData.properties && layerData.properties.length > 0) {
              KeyframeUtils.applyAnimations(layer, layerData.properties, fps);
            }

            // Apply enhanced features (effects, masks, blend modes, expressions)
            processLayerEnhancements(layer, layerData, fps);
          }
        }

        compMap[sceneData.id] = sceneComp;
        currentStep++;
      }

      // Step 2: Create main composition with precomps
      progress.children[0].text = 'Creating main composition...';
      progressBar.value = (currentStep / totalSteps) * 100;

      var mainComp = createMainComposition(meta);
      var mainCompData = manifest.compositions[0];

      if (mainCompData && mainCompData.layers) {
        // Add precomps in reverse order
        for (var k = mainCompData.layers.length - 1; k >= 0; k--) {
          var precompData = mainCompData.layers[k];

          if (precompData.type === 'precomp' && precompData.content) {
            var sourceComp = compMap[precompData.content.compositionId];
            if (sourceComp) {
              var precompLayer = mainComp.layers.add(sourceComp);
              precompLayer.name = precompData.name || 'Scene';
              precompLayer.inPoint = (precompData.inPoint || 0) / fps;
              precompLayer.outPoint = (precompData.outPoint || mainComp.duration * fps) / fps;
            }
          }
        }
      }

      progress.close();

      // Show success message
      var sceneCount = sceneComps.length;
      alert('Import Complete!\n\n' +
            'Composition: ' + meta.name + '\n' +
            'Duration: ' + meta.durationInSeconds.toFixed(2) + 's\n' +
            'FPS: ' + meta.fps + '\n' +
            'Scenes: ' + sceneCount + '\n\n' +
            'The composition has been created in your project panel.');

      return mainComp;

    } catch (e) {
      progress.close();
      alert('Import error: ' + e.message + '\nLine: ' + e.line);
      return null;
    }
  }

  // =====================
  // Main Entry Point
  // =====================

  function main() {
    // Check if we have a project
    if (!app.project) {
      alert('Please create or open a project first.');
      return;
    }

    // Prompt for manifest file
    var file = selectManifestFile();
    if (!file) {
      return; // User cancelled
    }

    // Read and parse manifest
    var manifest = readJsonFile(file);
    if (!manifest) {
      return; // Error already shown
    }

    // Validate manifest version
    if (manifest.version !== '1.0') {
      var proceed = confirm('This manifest was created with version ' + manifest.version +
                           ' but this importer supports version 1.0.\n\n' +
                           'Continue anyway?');
      if (!proceed) return;
    }

    // Process the manifest
    app.beginUndoGroup('Import Remotion Composition');
    try {
      processManifest(manifest);
    } finally {
      app.endUndoGroup();
    }
  }

  // Run main function
  main();

})();
